### ISSUE TITLE
Deposits App

### ISSUE THREAD

**Issue by burrrata** [1Hive/deposits-app#1]
The deposit forwarder allows Aragon organizations to require users place a deposit before forwarding an intent. The deposit amount and time locked are configurable by the organization. The user can reclaim their deposit after the time lock expires. 
This going to work as "middleware" app that filter intents that fulfill conditions. The forwarder has an interface (like voting), but rather than requiring a vote it just requires a deposit be locked up for some time. 
- Status: not under development

@0xGabi
- I agree on this as well. Sounds really interesting.

@lkngtn
- I imagine you generally support this since you added it to the original [HackMD doc](https://hackmd.io/vehSeyRTRS-I20hYMmOtGg)?

@burrrata 
- This sounds a lot like [PoS Conditional Hashcash](https://ethresear.ch/t/conditional-proof-of-stake-hashcash/1301) and that it might make sense to extend it with the option to burn the deposit/stake if the proposal is spam, but if not the person submitting a proposal gets their stake back. This would be very useful as decentralized spam reduction is something [top of mind for the CFDAO](https://forum.aragon.org/t/agp-idea-modify-the-agp-10-community-funding-dao-so-only-the-aragon-co-op-can-create-new-votes/727/19) and could benefit the broader Aragon/DAO ecosystem.
- /u/carlslarson (on Reddit) is [building a similar thing for Daonuts](https://www.reddit.com/r/daonuts/comments/bo6f85/alternate_option_for_registration_distribution/) (which is also an Aragon project) and suggested that this could also be turned into a challenge-response game where all submissions are approved by default, but if you flag something as spam and the broader community agrees with you there could be a small reward. If we want to move forward with this I think it makes sense to ask /u/carslarson if he wants to collaborate.
- Also, since we're exploring the design space of spam mitigation in social settings @vbuterin mentioned a few good ones [here](https://ethresear.ch/t/list-of-primitives-useful-for-using-cryptoeconomics-driven-internet-social-media-applications/3198) that are somewhat similar to what we're exploring, particularly the scorched earth anti-spam idea.

**Comment by lkngtn** [comment]
Closing this as the requirements have now been documented in the readme #2, and there is a seperate issue for estimation #3
